## 250126 update(LHC) - Category 1 (question)
question_text: |
  [{"CAM (Cathode Active Material)": {"Stoichiometry information": {"pristine NCM": {}, "M-NCM": {}, "NCM/graphite": {}, "M-NCM/graphite": {}}, "Commercial NCM used": {"pristine NCM": {}, "M-NCM": {}, "NCM/graphite": {}, "M-NCM/graphite": {}}, "Lithium source": null, "Synthesis method": null, "Crystallization method": null, "Crystallization final temperature": null, "Crystallization final duration (hours)": null, "Doping": null, "Coating": null}}]

template: 
  CAM (Cathode Active Material): 
    Stoichiometry information: {}
    Commercial NCM used: {}
    Lithium source: null
    Synthesis method: null
    Crystallization method: null
    Crystallization final temperature: null
    Crystallization final duration (hours): null
    Doping: null
    Coating: null